title: Wang's site
author: Wang
email: 26547614+nocwang@users.noreply.github.com
description: > # this means to ignore newlines until "baseurl:"
  keep records of good ideas

# social links
twitter_username: nocwang # DO NOT include the @ character, or else the build will fail!
github_username:  nocwang # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: Hyde #minima
